<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Activitystream
 * @version    1.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><span class="ActivityRecord">
    <?php foreach ($this->getParts() as $__part): ?>
        <?php if ($__part->getType() == AW_Activitystream_Block_ActivityRecord::PART_TYPE_PLAINTEXT): ?>
            <?php echo str_replace(' ', '&nbsp;', htmlspecialchars($__part->getContent())) ?>
        <?php endif; ?>
        <?php if ($__part->getType() == AW_Activitystream_Block_ActivityRecord::PART_TYPE_VARIABLE): ?>
            <?php if ($__part->getUrl()): ?>
                <a href="<?php echo $__part->getUrl() ?>">
            <?php else: ?>
                <?php if ( ! $__part->getIsValueDefault() ): ?>
                    <b>
                <?php endif; ?>
            <?php endif; ?>
            
            <?php echo str_replace(' ', '&nbsp;', htmlspecialchars($__part->getValue())) ?>
            
            <?php if ($__part->getUrl()): ?>
                </a>
            <?php else: ?>
                <?php if ( ! $__part->getIsValueDefault() ): ?>
                    </b>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</span>