<script type="text/javascript">
//<![CDATA[
	var auctionTimeCounters = new Array();
	var i = 0;
//]]>
</script>	
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php $_helper = $this->helper('catalog/output') ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no auction products.') ?>
</div>
<?php else: ?>
<?php $now_time = Mage::getModel('core/date')->timestamp(time()) ?>
<?php $modelAuction = Mage::getModel('auction/productauction') ?>
<section id="daily_deals">
<h2>Monthly Deals</h2>
	<?php $_collectionSize = $_productCollection->count() ?>
    <ul>
	<?php foreach ($_productCollection as $_product): ?>
		<?php $auction	= $modelAuction->loadAuctionByProductId($_product->getId()) ?>
		<?php $lastBid = $auction->getLastBid() ?>
		<?php $totalBid = $auction->getTotalBid() ?>
		<?php $currentPrice = $lastBid->getPrice() ? $lastBid->getPrice() : $auction->getInitPrice() ?>	
		<?php $end_time = strtotime($auction->getEndTime() .' '. $auction->getEndDate()) ?>	
		<?php $url_history = $this->getHistoryUrl($auction); ?>
		 <li>
<section class="prod_img"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(142,122); ?>" width="142" height="122" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></section>
<section class="title"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></section>
<section class="daily_deals_price"> <?php echo $this->getPriceHtml($_product, true) ?>
 <input type="button" class="buy_it_now_btn" value="Buy Now" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
 <section class="listing_time"><div class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>	
					<div id="auction_info_<?php echo $_product->getId()?>">				
						<div class="row">
							<span class="current_price" id="current_price<?php echo $_product->getId()?>">
								Current Bid Price: <br><?php echo Mage::helper('core')->currency($currentPrice) ?>
							</span>
							<div class="clear">&nbsp;</div>
						</div>
						<div class="row">
							<span class="bidder" id="bidder<?php echo $_product->getId()?>">
								<?php echo $lastBid ? $lastBid->getBidderName() : $this->__('None') ?>
							</span>
							<div class="clear">&nbsp;</div>
						</div>	
						<input type="hidden" id="codecolor<?php echo $_product->getId()?>" name="codecolor" value="0"  >		
						<input type="hidden" id="current_bid_id_<?php echo $_product->getId() ?>" value="<?php echo $lastBid->getId() ?>" />
					</div>
					<div id="results_update_auction_<?php echo $_product->getId() ?>" style="display:none;"></div></section></section>
                   

</li>




		<script type="text/javascript">
		//<![CDATA[
			auctionTimeCounters[i] = new AuctionTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $auction->getId() ?>', '<?php echo $this->__(' day, ') ?>', '<?php echo $this->__(' days, ') ?>', '<?php echo $this->__(' month, ') ?>', '<?php echo $this->__(' months, ') ?>', '<?php echo $this->__(' year, ') ?>', '<?php echo $this->__(' years, ') ?>');
			auctionTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
			updateAuctionListInfo('auction_info_<?php echo $_product->getId() ?>','<?php echo Mage::getBaseUrl('js') ?>magestore/auction.php?<?php echo http_build_query(array('tmpl' => 'auctionlistinfo')) ?>','<?php echo $_product->getId() ?>','<?php echo $auction->getId() ?>');
			i++;
			setBackground('current_price','<?php echo $_product->getId() ?>');	
			setBackground('bidder','<?php echo $_product->getId() ?>');
		//]]>
		</script>
		<div id="init_price<?php echo $_product->getId()?>" style="display: none;">
			<?php echo Mage::helper('core')->currency($auction->getInitPrice()) ?>
		</div>
   <?php endforeach ?>
	</ul>
    <script type="text/javascript">
		decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);
		
		<?php
		$baseCurrency = Mage::app()->getStore()->getBaseCurrency();
		$currCurrency = Mage::app()->getStore()->getCurrentCurrency();
		?>
		var currencyConvert = new CurrencyConvert('<?php echo $baseCurrency->format(1000,array(),false) ?>','<?php echo $currCurrency->format(1000,array(),false) ?>',<?php echo Mage::app()->getStore()->convertPrice(1) ?>);
	</script>
</div>
<?php endif; ?>

<style type="text/css">	
	<?php echo Mage::getStoreConfig('auction/design/css') ?>
</style>
