<div class="page-title">
	<h1><?php echo $this->__('My Bids') ?></h1>
</div>

<div class="note-msg">
    <?php echo $this->__('You have not a bidder name to use in our Auction system! Please create a bidder nickname by form bellow')?>
</div>

<form id="form-bidder" name="form-bidder" action="<?php echo $this->getUrl('auction/index/savebiddername',array())?>" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Enter Bidder Name') ?></h2>
        <div class="form-list">
            <label for="content" class="required"><?php echo $this->__('Bidder Name') ?><em>*</em></label>
            <div class="input-box">
				<input type="input" id="bidder_name" name="bidder_name" class="required-entry input-text"/>
      		</div>
            <span id="biddername-please-wait" style="display:none;" class="opc-please-wait">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> 
                &nbsp; <?php echo $this->__('waiting') ?>...
            </span>	
            <div id="bidder-notice">
                <input type="hidden" value="0" id="is_valid_bidder_name">
            </div>
            <div class="clear fix">&nbsp;</div>
         </div>   			
    </div>
    <div class="row" id="bidder_name_form_button" style="display:none;">
        <button type="button" class="button" style="float:right" onclick="checkBidderNameForm();">
            <span><?php echo $this->__('Create')?></span>
        </button>
    </div>
</form>

<div class="clear fix">&nbsp;</div>	
<div class="button-set">
	<a class="left" href="javascript:history.go(-1);"> <?php echo $this->__('Back') ?></a>
</div>

<script type="text/javascript">
//<![CDATA[
	var bidderForm = new VarienForm('form-bidder', true);
	
	var auction = new Auction('<?php echo $this->getUrl('auction/index/checkbiddername',array()) ?>');

	Event.observe('bidder_name', 'change', function(event){ 
			auction.checkBidderName();
	});	

	function checkBidderNameForm()
	{
		if($('is_valid_bidder_name').value =='0')
		{
			alert('Please enter bidder name');
			return false;
		}
		
		if($('is_valid_bidder_name').value =='2')
		{
			alert('The name is existed');
			return false;
		}
		bidderForm.submit();	
	}

//]]>
</script>	

<style type="text/css">	
	<?php echo Mage::getStoreConfig('auction/design/css') ?>
</style>	
