<!doctype html>
<html>
<head>
<?php echo $this->getChildHtml('head')?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.7.1.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/modernizr.custom.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/easyResponsiveTabs.js')?>" type="text/javascript"></script>
</head>

<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<!-- BEGIN GOOGLE ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    var _gaq = _gaq || [];
    
_gaq.push(['_setAccount', 'UA-16361415-1']);
_gaq.push(['_trackPageview']);
    
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

//]]>
</script>
<!-- END GOOGLE ANALYTICS CODE -->
<?php echo $this->getChildHtml('header')?>
<section id="center_area">
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $currentCategory = Mage::registry('current_category') ?>
<?php $displayMode = $currentCategory->getDisplayMode();?>
<?php if ($displayMode=='PAGE'):?>
<aside><?php echo $this->getChildHtml('left')?>
</aside>
<section id="right_side_area">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>
</section>
<?php else:?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>
<?php endif;?>
</section>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
