<?php
	$customer = $this->getCustomer();
	$auctionbid = $this->getAuctionbid();
	$customer_url = $this->getCustomerUrl($auctionbid->getCustomerId());
		
?>

<center>
<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-account"><?php echo $this->__('Customer Information')?></h4>
		</div>
		<div class="fieldset">
			<table class="form-list" cellspacing="0">
				<tr>
					<td class="label"><label><?php echo $this->__('Bidder Name') ?></label></td>
					<td><strong><?php echo $auctionbid->getBidderName() ?></strong></td>
				</tr>				
				<tr>
					<td class="label"><label><?php echo $this->__('Customer Name') ?></label></td>
					<td><strong><?php echo $auctionbid->getCustomerName() ?></strong></td>
				</tr>
				<tr>
					<td class="label"><label><?php echo $this->__('Customer Email') ?></label></td>
					<td><strong><?php echo $auctionbid->getCustomerEmail()?></strong></td>
				</tr>
				<tr>
					<td class="label"><label><?php echo $this->__('Customer Phone') ?></label></td>
					<td><strong><?php echo $auctionbid->getCustomerPhone()?></strong></td>
				</tr>
				<tr>
					<td class="label"><label><?php echo $this->__('Customer Address') ?></label></td>
					<td><strong><?php echo $auctionbid->getCustomerAddress() ?></strong></td>
				</tr>
				<tr>
					<td class="label"><label><?php echo $this->__('Customer Detail') ?></label></td>
					<td><strong><a target="_blank" href="<?php echo $customer_url ?>"> <?php echo $this->__('view') ?></a></strong></td>
				</tr>								
			</table>
		</div>
	</div>
</div>
</center>