<script type="text/javascript">
//<![CDATA[
	
	var auctionTimeCounters = new Array();
	var i = 0;
//]]>
</script>	
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no auction products.') ?>
</div>
<?php else: ?>
<?php $now_time = Mage::getModel('core/date')->timestamp(time()) ?>
<?php $modelAuction = Mage::getModel('auction/productauction') ?>
<div class="grid-full breadcrumbs">
    <ul>
                    <li class="home">
                            <a href="http://noworriesturf.undergroundonlinestores.com.au/index.php/" title="Go to Home Page">Home</a>
                                        <span>/ </span>
                        </li>
                    <li class="category39">
                            <strong> Auctions</strong>
                                    </li>
            </ul>
</div>
<div class="page-title category-title grid-full">
        <h1> Auction Products</h1>
</div>

<div class="category-products">
<?php echo $this->getToolbarHtml() ?>


<?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if($i++%$_columnCount==0): ?>
        <ul class="products-grid category-products-grid itemgrid itemgrid-3cols hover-effect equal-height">
        <?php endif; ?>
	<?php $auction	= $modelAuction->loadAuctionByProductId($_product->getId()) ?>
	<?php $lastBid = $auction->getLastBid() ?>
	<?php $totalBid = $auction->getTotalBid() ?>
	<?php $currentPrice = $lastBid->getPrice() ? $lastBid->getPrice() : $auction->getInitPrice() ?>	
	<?php $end_time = strtotime($auction->getEndTime() .' '. $auction->getEndDate()) ?>	
	<?php $url_history = $this->getHistoryUrl($auction); ?>
			<li class="item">
                <p class="product-image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                </p>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
					<?php echo $this->htmlEscape($_product->getName()) ?></a>
				</h2>
                <div class="price-box">
					<p class="old-price"> <span class="price-label">NORMAL RETAIL :</span>
					<span class='price' id='old-price'><?php echo $this->getPriceHtml($_product, true); ?></span>
					</p>
				</div>
                
			<div class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>	
			<div id="auction_info_<?php echo $_product->getId()?>">				
				<div class="row"> <center>
					<span class="current_price" id="current_price<?php echo $_product->getId()?>">
						<?php echo Mage::helper('core')->currency($currentPrice) ?>
					</span> </center>
					<div class="clear"></div>
				</div>
				<div class="row"> <center>
					<span class="bidder" id="bidder<?php echo $_product->getId()?>"> 
						<?php //echo $lastBid ? $lastBid->getBidderName() : $this->__('None'); 
						      if ($lastBid){
						         if($lastBid->getBidderName()!=''){
						               echo "By ".$lastBid->getBidderName();
						           }else{
						               echo "";
						           }
						      }else{
						           echo $this->__('None');
						      }
						?>
					</span> </center>
					<div class="clear"></div>
				</div>	
				<input type="hidden" id="codecolor<?php echo $_product->getId()?>" name="codecolor" value="0"  >		
				<input type="hidden" id="current_bid_id_<?php echo $_product->getId() ?>" value="<?php echo $lastBid->getId() ?>" />
			</div>
			<div id="results_update_auction_<?php echo $_product->getId() ?>" style="display:none;">
			</div>
			<div id="init_price<?php echo $_product->getId()?>" style="display: none;">
		<?php echo Mage::helper('core')->currency($auction->getInitPrice()) ?>
	</div>
		</li>
<script type="text/javascript">
//<![CDATA[
	auctionTimeCounters[i] = new AuctionTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $auction->getId() ?>', 

'<?php echo $this->__(' day, ') ?>', '<?php echo $this->__(' days, ') ?>', '<?php echo $this->__(' month, ') ?>', '<?php echo $this->__(' months, ') ?>', '<?php 

echo $this->__(' year, ') ?>', '<br><?php echo $this->__(' years, ') ?>');
	auctionTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
	updateAuctionListInfo('auction_info_<?php echo $_product->getId() ?>','<?php echo Mage::getBaseUrl('js') ?>magestore/auction.php?<?php 

echo http_build_query(array('tmpl' => 'auctionlistinfo')) ?>','<?php echo $_product->getId() ?>','<?php echo $auction->getId() ?>');
	i++;
	setBackground('current_price','<?php echo $_product->getId() ?>');	
	setBackground('bidder','<?php echo $_product->getId() ?>');
//]]>
</script>			
        <?php if($i%$_columnCount==0 || $i==$_collectionSize): ?>
	</ul>
	<div class="clear"></div>
        <?php endif; ?>
	
    <?php endforeach ?>
    <script type="text/javascript">
		decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);
		<?php
		$baseCurrency = Mage::app()->getStore()->getBaseCurrency();
		$currCurrency = Mage::app()->getStore()->getCurrentCurrency();
		?>
		var currencyConvert = new CurrencyConvert('<?php echo $baseCurrency->format(1000,array(),false) ?>','<?php echo $currCurrency->format(1000,array(),false) ?>',<?php echo Mage::app()->getStore()->convertPrice(1) ?>);
		
	</script>
</div>
<?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
<style type="text/css">	
	<?php echo Mage::getStoreConfig('auction/design/css') ?>
</style>
